name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    uses: SamuelMarks/c-ci/.github/workflows/c-cmake-ci.yml@master
    with:
      cmake_configure_flags: '-DC89STRINGUTILS_BUILD_AMALGAMATION=ON'
      project_name: 'c89stringutils'

  test-amalg:
    name: Test Amalgamation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate amalgamation
        run: |
          cmake -B build -DC89STRINGUTILS_BUILD_AMALGAMATION=ON
          cmake --build build

      - name: Compile Test Amalgamation
        run: gcc -Wall -Wextra -Werror -Ibuild -o test_amalg c89stringutils/tests/test_amalg.c

      - name: Run Test Amalgamation
        run: ./test_amalg
