name: Linux, Windows, macOS, SunOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: mkdir
        run: mkdir build
      - name: build
        working-directory: ./build
        run: |
          cmake -DCMAKE_BUILD_TYPE="Debug" ..
          cmake --build .
      - name: test
        working-directory: ./build
        run: ctest -C Debug .

  testsolaris:
    runs-on: macos-10.15
    name: Solaris
    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        id: build_test
        uses: vmactions/solaris-vm@v0.0.3
        with:
          prepare: pkgutil -y -i cmake
        run: |
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE="Debug" ..
          cmake --build .
          ctest -C Debug .
