name: CI for Linux, Windows, macOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: mkdir
        run: mkdir build
      - name: build
        working-directory: ./build
        run: |
          cmake -DCMAKE_BUILD_TYPE="Debug" ..
          cmake --build .
      - name: test
        working-directory: ./build
        run: ctest -C Debug .
