name: Linux, Windows, macOS, SunOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-10.15]

    name: ${{ matrix.os == 'macos-10.15' && 'SunOS' || 'macOS' }}

    steps:
      - uses: actions/checkout@v2
      - name: mkdir
        run: mkdir build
      - name: SunOS deps
        id: build_test
        uses: papertigers/illumos-vm@r38
        with:
          prepare: pkg install cmake
          run: |
            mkdir build && cd build
            /opt/ooce/bin/cmake -DCMAKE_BUILD_TYPE="Debug" ..
            /opt/ooce/bin/cmake --build .
            /opt/ooce/bin/ctest -C Debug .
        if: matrix.os == 'macos-10.15'
      - name: build
        working-directory: ./build
        run: |
          cmake -DCMAKE_BUILD_TYPE="Debug" ..
          cmake --build .
        if: matrix.os != 'macos-10.15'
      - name: test
        working-directory: ./build
        run: ctest -C Debug .
        if: matrix.os != 'macos-10.15'
